CREATE DATABASE TERRITORIO_RICA;
USE TERRITORIO_RICA;
-- -------------------------------------------------------------------------------
CREATE TABLE USUARIO
(
USU_CVE_USUARIO		INT 		NOT NULL	PRIMARY KEY AUTO_INCREMENT,
USU_NOMBRE		VARCHAR(30) 	NOT NULL,
USU_APELLIDO_PATERNO	VARCHAR(30) 	NOT NULL,
USU_APELLIDO_MATERNO	VARCHAR(30) 	NOT NULL,
USU_EDAD	INT	NOT NULL,
USU_CORREO		VARCHAR(40) 	NOT NULL,
USU_USUARIO		VARCHAR(30) 	NOT NULL,
USU_CONTRASENA		VARCHAR(20) 	NOT NULL,
USU_TELEFONO		VARCHAR(10) 	NOT NULL,
USU_RUTAIMAGEN		VARCHAR(200) 	NOT NULL,
CVE_ZONA_ASIGNADA	INT 		NOT NULL,
FOREIGN KEY (CVE_ZONA_ASIGNADA) REFERENCES ZONA_ASIGNADA(CVE_ZONA_ASIGNADA) 
);
-- -------------------------------------------------------------------------------
CREATE TABLE ZONA_ASIGNADA
(
CVE_ZONA_ASIGNADA	INT 		NOT NULL	PRIMARY KEY AUTO_INCREMENT,
TIPO_DESCRIPCION		VARCHAR(100) 	NOT NULL
);
-- -------------------------------------------------------------------------------
CREATE TABLE GERENTE
(
GER_CVE_GERENTE		INT 		NOT NULL	PRIMARY KEY AUTO_INCREMENT,
GER_NOMBRE		VARCHAR(30) 	NOT NULL,
GER_APELLIDO_PATERNO	VARCHAR(30) 	NOT NULL,
GER_APELLIDO_MATERNO	VARCHAR(30) 	NOT NULL,
GER_EDAD	INT	NOT NULL,
GER_CORREO		VARCHAR(40) 	NOT NULL,
GER_USUARIO		VARCHAR(30) 	NOT NULL,
GER_CONTRASENA		VARCHAR(20) 	NOT NULL,
GER_TELEFONO		VARCHAR(10) 	NOT NULL,
GER_NSS		VARCHAR(30) 	NOT NULL,
GER_CURP		VARCHAR(30) 	NOT NULL,
GER_RFC		VARCHAR(30) 	NOT NULL,
GER_RUTAIMAGEN		VARCHAR(200) 	NOT NULL,
CVE_AREA_TRABAJO	INT 		NOT NULL,
FOREIGN KEY (CVE_AREA_TRABAJO) REFERENCES AREA_TRABAJO(CVE_AREA_TRABAJO) 
);
-- -------------------------------------------------------------------------------
CREATE TABLE AREA_TRABAJO
(
CVE_AREA_TRABAJO	INT 		NOT NULL	PRIMARY KEY AUTO_INCREMENT,
TRA_TIPO_DESCRIPCION		VARCHAR(100) 	NOT NULL
);
-- -------------------------------------------------------------------------------
CREATE TABLE CATEGORIA_PRODUCTOS
(
CVE_CATEGORIA	INT 		NOT NULL	PRIMARY KEY AUTO_INCREMENT,
CATE_NOMBRE		VARCHAR(50) 	NOT NULL,
CATE_TIPO_DESCRIPCION		VARCHAR(100) 	NOT NULL
);
-- -------------------------------------------------------------------------------
CREATE TABLE CATALOGO_PRODUCTOS
(
CVE_CATALOGO	INT 		NOT NULL	PRIMARY KEY AUTO_INCREMENT,
CATA_NOMBRE		VARCHAR(50) 	NOT NULL,
CVE_CATEGORIA	INT 		NOT NULL,
CATA_PRECIO		DECIMAL(4, 2) 	NOT NULL,
CATA_CODIGO_BARRAS		VARCHAR(12) 	NOT NULL,
FOREIGN KEY (CVE_CATEGORIA) REFERENCES CATEGORIA_PRODUCTOS(CVE_CATEGORIA) 
);
-- -------------------------------------------------------------------------------
CREATE TABLE CANAL_VENTA
(
CVE_CANAL INT 		NOT NULL	PRIMARY KEY AUTO_INCREMENT,
VEN_TIPO_DESCRIPCION		VARCHAR(100) 	NOT NULL
);
-- -------------------------------------------------------------------------------
CREATE TABLE CATALOGO_SKU (
    CVE_SKU INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SKU_NUMERO VARCHAR(12) NOT NULL,
    SKU_NOMBRE_COMERCIAL VARCHAR(50) NOT NULL,
    CVE_CATEGORIA INT NOT NULL,
    SKU_VOLUMEN_ML INT NOT NULL,
    SKU_EMPAQUETADO VARCHAR(100) NOT NULL,
    CVE_CATALOGO INT NOT NULL,
    CVE_CANAL INT NOT NULL,
    SKU_STOCK INT NOT NULL,
    SKU_RUTAIMAGEN VARCHAR(200) 	NOT NULL,
    FOREIGN KEY (CVE_CATEGORIA) REFERENCES CATEGORIA_PRODUCTOS(CVE_CATEGORIA),
    FOREIGN KEY (CVE_CATALOGO) REFERENCES CATALOGO_PRODUCTOS(CVE_CATALOGO),
    FOREIGN KEY (CVE_CANAL) REFERENCES CANAL_VENTA(CVE_CANAL)
);
-- -------------------------------------------------------------------------------
CREATE TABLE VENTAS
(
CVE_VENTAS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
VEN_FECHA DATE,
CVE_SKU INT NOT NULL,
VEN_CANTIDAD INT NOT NULL,
VEN_PRECIO_UNITARIO DECIMAL(4, 2) 	NOT NULL,
VEN_COSTO_UNITARIO DECIMAL(4, 2) 	NOT NULL,
CVE_CANAL INT NOT NULL,
VEN_TOTAL_VENTA DECIMAL(10, 2) 	NOT NULL,
FOREIGN KEY (CVE_SKU) REFERENCES CATALOGO_SKU(CVE_SKU),
FOREIGN KEY (CVE_CANAL) REFERENCES CANAL_VENTA(CVE_CANAL)
);